server:
  port: 8000

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
mybatis:
  type-aliases-package: com.bision.subway.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-caml-case: true
logging:
  level:
    root: INFO
    com.example.myspringapp: DEBUG # 특정 패키지의 로그 레벨 설정