server:
  port: 8000

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: INFO
    com.example.myspringapp: DEBUG # 특정 패키지의 로그 레벨 설정